// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUDY0T3y0oqnE3C5nW5ut15O5Ea2J3wfQ',
    appId: '1:1070916759169:web:106a66e320619bc1a2a780',
    messagingSenderId: '1070916759169',
    projectId: 'visionprice-f756e',
    authDomain: 'visionprice-f756e.firebaseapp.com',
    storageBucket: 'visionprice-f756e.firebasestorage.app',
    measurementId: 'G-5B4F0Y4KTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADVLl9P_KWQR1es5_z83Af9pX__ej8hm8',
    appId: '1:1070916759169:android:908496588a9580dca2a780',
    messagingSenderId: '1070916759169',
    projectId: 'visionprice-f756e',
    storageBucket: 'visionprice-f756e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQOc1WC_fhu62pOl6N1QDSBS31BnwZLzI',
    appId: '1:1070916759169:ios:7e2b284b5481eaf9a2a780',
    messagingSenderId: '1070916759169',
    projectId: 'visionprice-f756e',
    storageBucket: 'visionprice-f756e.firebasestorage.app',
    iosBundleId: 'com.example.scanbuild',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQOc1WC_fhu62pOl6N1QDSBS31BnwZLzI',
    appId: '1:1070916759169:ios:7e2b284b5481eaf9a2a780',
    messagingSenderId: '1070916759169',
    projectId: 'visionprice-f756e',
    storageBucket: 'visionprice-f756e.firebasestorage.app',
    iosBundleId: 'com.example.scanbuild',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUDY0T3y0oqnE3C5nW5ut15O5Ea2J3wfQ',
    appId: '1:1070916759169:web:2ffbe4be7aaba644a2a780',
    messagingSenderId: '1070916759169',
    projectId: 'visionprice-f756e',
    authDomain: 'visionprice-f756e.firebaseapp.com',
    storageBucket: 'visionprice-f756e.firebasestorage.app',
    measurementId: 'G-5NSXS9SE05',
  );
}
